// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PMatCParallel
NumericMatrix PMatCParallel(NumericMatrix xMat, int d, NumericVector Values);
RcppExport SEXP _StructDivDevel_PMatCParallel(SEXP xMatSEXP, SEXP dSEXP, SEXP ValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xMat(xMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Values(ValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(PMatCParallel(xMat, d, Values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StructDivDevel_PMatCParallel", (DL_FUNC) &_StructDivDevel_PMatCParallel, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StructDivDevel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
